// <auto-generated />
using System;
using AnLabb4.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnLabb4.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AN_Labb_4.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Hockey is a team based sport played 5v5 + a goalie",
                            InterestTitle = "Hockey"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Floorball is a team based sport played 5v5 + a goalie",
                            InterestTitle = "Floorball"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "League of legends is a team based strategy computer game played 5v5",
                            InterestTitle = "LeagueOfLegends"
                        });
                });

            modelBuilder.Entity("AN_Labb_4.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Anas",
                            LastName = "Qlok",
                            PhoneNumber = "072542302"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Tobias",
                            LastName = "Qlok",
                            PhoneNumber = "0734242"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Reidar",
                            LastName = "Qlok",
                            PhoneNumber = "074241"
                        });
                });

            modelBuilder.Entity("AN_Labb_4.PersonInterestLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InterestId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("PersonInterestLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 2,
                            PersonId = 1,
                            WebsiteId = 2
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 1,
                            PersonId = 2,
                            WebsiteId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 3,
                            WebsiteId = 3
                        });
                });

            modelBuilder.Entity("AN_Labb_4.Website", b =>
                {
                    b.Property<int>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebsiteId");

                    b.ToTable("Websites");

                    b.HasData(
                        new
                        {
                            WebsiteId = 1,
                            Link = "https://www.laget.se/KungsbackaHC"
                        },
                        new
                        {
                            WebsiteId = 2,
                            Link = "https://www.varlaibk.nu/start/?ID=16231"
                        },
                        new
                        {
                            WebsiteId = 3,
                            Link = "https://www.leagueoflegends.com/en-gb/"
                        });
                });

            modelBuilder.Entity("AN_Labb_4.PersonInterestLink", b =>
                {
                    b.HasOne("AN_Labb_4.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId");

                    b.HasOne("AN_Labb_4.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("AN_Labb_4.Website", "Website")
                        .WithMany()
                        .HasForeignKey("WebsiteId");
                });
#pragma warning restore 612, 618
        }
    }
}
